// v3.6.0 — 2026-04-03

// ─── app-a-family-hub/js/screens/travel-summary.js ────────────────────────
// Generates accurate, single-passenger pivot summaries of travel days.

'use strict';

import { 
  formatDisplayDate, daysBetween, copyToClipboard, showToast,
  today
} from '../../../shared/utils.js';

export function renderTravelSummarySheet(uniquePassengers, trips, defaultYear, defaultPassenger) {
  let sheet = document.getElementById('travel-summary-sheet');
  if (!sheet) {
    sheet = document.createElement('div');
    sheet.id = 'travel-summary-sheet';
    sheet.className = 'export-sheet';
    document.body.appendChild(sheet);
  }

  // Parse defaultPassenger, which might be a comma-separated list
  let initialPass = uniquePassengers.length > 0 ? uniquePassengers[0].name : '';
  if (defaultPassenger) {
    const arr = defaultPassenger.split(',').filter(Boolean);
    if (arr.length > 0) initialPass = arr[0].trim();
  }

  // State
  const state = {
    selectedPassenger: initialPass,
    pivotMode: 'year' // 'year' or 'country'
  };

  function renderUI() {
    // Generate Summary Data
    const summaryData = computeSummaryData();

    sheet.innerHTML = `
      <div class="app-header" style="background:var(--surface);">
        <button class="app-header-action" id="close-summary-btn">✕</button>
        <span class="app-header-title">📊 Travel Summary Card</span>
        <span style="width:32px;"></span>
      </div>

      <div style="padding:16px;overflow-y:auto;flex:1;background:var(--page-bg);padding-bottom:100px;">
        
        <!-- Filters -->
        <div style="background:var(--surface);border-radius:var(--radius-lg);padding:16px;margin-bottom:16px;border:1px solid var(--border);">
          <div style="font-size:13px;font-weight:700;color:var(--text-muted);margin-bottom:8px;text-transform:uppercase;">Select Passenger</div>
          <select id="sum-pass-select" class="form-input" style="margin-bottom:16px;background-color:var(--surface);border:1px solid var(--border);">
            ${uniquePassengers.map(p => `
              <option value="${p.name}" ${state.selectedPassenger === p.name ? 'selected' : ''}>${p.emoji || '👤'} ${p.name}</option>
            `).join('')}
          </select>

          <div style="font-size:13px;font-weight:700;color:var(--text-muted);margin-bottom:8px;text-transform:uppercase;">View Style</div>
          <div style="display:flex;background:var(--surface-3);border-radius:var(--radius-md);padding:4px;">
            <button class="btn ${state.pivotMode === 'year' ? 'btn-primary' : 'btn-secondary'}" style="flex:1;padding:6px;font-size:13px;" id="mode-year-btn">Pivot by Year</button>
            <button class="btn ${state.pivotMode === 'country' ? 'btn-primary' : 'btn-secondary'}" style="flex:1;padding:6px;font-size:13px;" id="mode-country-btn">Pivot by Country</button>
          </div>
        </div>

        <!-- Rendered Summary -->
        <div id="summary-render-target">
          <div style="background:var(--surface);border-radius:var(--radius-lg);padding:16px;border:1px solid var(--border);">
            <div style="text-align:center;margin-bottom:16px;border-bottom:1px solid var(--border-light);padding-bottom:16px;">
              <div style="font-size:36px;margin-bottom:8px;">${getEmoji(state.selectedPassenger)}</div>
              <h2 style="margin:0;font-size:20px;">${state.selectedPassenger}</h2>
              <p style="margin:4px 0 0;font-size:12px;color:var(--text-muted);">
                Travel Summary <br/> <span style="opacity:0.7">(Days grouped by trip entry date)</span>
              </p>
            </div>

            <div style="padding:0 8px;">
              ${renderPivot(summaryData)}
            </div>
            
            <div style="text-align:center;margin-top:24px;font-size:10px;color:var(--text-muted);text-transform:uppercase;letter-spacing:1px;">
              Generated by Family Hub
            </div>
          </div>
        </div>

      </div>

      <!-- Action Bar -->
      <div style="position:absolute;bottom:0;left:0;right:0;padding:16px;background:var(--surface);border-top:1px solid var(--border);display:flex;gap:12px;">
         <button class="btn btn-secondary" style="flex:1;display:flex;flex-direction:column;align-items:center;padding:8px 0;" id="sum-export-txt">
           <span style="font-size:18px;margin-bottom:2px;">📋</span><span style="font-size:11px;">Copy Txt</span>
         </button>
         <button class="btn btn-secondary" style="flex:1;display:flex;flex-direction:column;align-items:center;padding:8px 0;" id="sum-export-image">
           <span style="font-size:18px;margin-bottom:2px;">📸</span><span style="font-size:11px;">Image</span>
         </button>
         <button class="btn btn-primary" style="flex:2;display:flex;flex-direction:column;align-items:center;padding:8px 0;" id="sum-share-wa">
           <span style="font-size:18px;margin-bottom:2px;">💬</span><span style="font-size:11px;">WhatsApp</span>
         </button>
      </div>
    `;

    // Listeners
    sheet.querySelector('#close-summary-btn').addEventListener('click', () => {
      sheet.classList.remove('open');
      setTimeout(() => sheet.remove(), 300);
    });

    sheet.querySelector('#sum-pass-select').addEventListener('change', (e) => {
      state.selectedPassenger = e.target.value;
      renderUI();
    });

    sheet.querySelector('#mode-year-btn').addEventListener('click', () => { state.pivotMode = 'year'; renderUI(); });
    sheet.querySelector('#mode-country-btn').addEventListener('click', () => { state.pivotMode = 'country'; renderUI(); });

    sheet.querySelector('#sum-export-txt').addEventListener('click', () => copyTextReport(summaryData));
    sheet.querySelector('#sum-export-image').addEventListener('click', () => exportImage());
    sheet.querySelector('#sum-share-wa').addEventListener('click', () => shareWhatsApp(summaryData));
  }

  function getEmoji(name) {
    const p = uniquePassengers.find(x => x.name === name);
    return p ? (p.emoji || '👤') : '👤';
  }

  // ─── Data Engine ────────────────────────────────────────────────────────
  function computeSummaryData() {
    if (!state.selectedPassenger) return { pivotYear: {}, pivotCountry: {} };

    // Find trips involving this passenger
    const pNameLower = state.selectedPassenger.toLowerCase();
    const pTrips = trips.filter(t => {
      const prim = String(t.passengerName || '').toLowerCase() === pNameLower;
      const travelWithNames = (Array.isArray(t.travelWith) ? t.travelWith : String(t.travelWith || '').split(/[,;]+/))
        .map(n => String(n || '').trim().toLowerCase());
      return prim || travelWithNames.includes(pNameLower);
    });

    const records = [];

    pTrips.forEach(t => {
      // Grouping by entry dates. E.g. dateArrivedDest
      const entryDt = t.dateArrivedDest || t.dateLeftOrigin;
      if (!entryDt) return;
      
      const year = entryDt.substring(0, 4);
      let days = t.daysInDest !== undefined && t.daysInDest !== null && t.daysInDest !== '' ? Number(t.daysInDest) : null;
      
      if (days === null || isNaN(days)) {
        let leftMs;
        if (t.dateLeftDest) leftMs = new Date(t.dateLeftDest).getTime();
        else leftMs = new Date(today()).getTime();
        
        const arrMs = new Date(entryDt).getTime();
        if (!isNaN(arrMs) && !isNaN(leftMs) && leftMs >= arrMs) {
          // +1 to count inclusive days (e.g., entered on 1st, left on 2nd = 2 days)
          days = Math.floor((leftMs - arrMs) / (1000 * 60 * 60 * 24)) + 1;
        } else {
          days = 0;
        }
      }
      
      if (days > 0) {
        const country = t.destinationCountry || 'Qatar';
        records.push({ year, country, days });
      }
    });

    // Generate grouping structures
    const pivotYear = {}; // e.g. { '2024': { 'Qatar': 15, 'India': 5 } }
    const pivotCountry = {}; // e.g. { 'Qatar': { '2024': 15, '2025': 20 } }

    records.forEach(r => {
      if (!pivotYear[r.year]) pivotYear[r.year] = {};
      pivotYear[r.year][r.country] = (pivotYear[r.year][r.country] || 0) + r.days;

      if (!pivotCountry[r.country]) pivotCountry[r.country] = {};
      pivotCountry[r.country][r.year] = (pivotCountry[r.country][r.year] || 0) + r.days;
    });

    return { pivotYear, pivotCountry };
  }

  function renderPivot(data) {
    if (Object.keys(data.pivotYear).length === 0) {
      return '<div style="text-align:center;padding:20px;color:var(--text-muted);font-size:14px;">No travel recorded for this passenger.</div>';
    }

    let html = '';
    
    if (state.pivotMode === 'year') {
      const years = Object.keys(data.pivotYear).sort((a,b) => b - a); // Descending Years
      years.forEach(y => {
        html += `<div style="margin-bottom:16px;">`;
        html += `<div style="font-size:15px;font-weight:700;color:var(--text);margin-bottom:6px;border-bottom:1px solid var(--border-light);padding-bottom:4px;">Year ${y}</div>`;
        const countries = Object.keys(data.pivotYear[y]).sort((a,b) => data.pivotYear[y][b] - data.pivotYear[y][a]);
        countries.forEach(c => {
          html += `
            <div style="display:flex;justify-content:space-between;padding:6px 0;">
              <span style="font-size:14px;color:var(--text-secondary);">${c}</span>
              <span style="font-size:14px;font-weight:700;color:var(--primary);">${data.pivotYear[y][c]} <span style="font-size:11px;font-weight:500;">days</span></span>
            </div>
          `;
        });
        html += `</div>`;
      });
    } else {
      const countries = Object.keys(data.pivotCountry).sort();
      countries.forEach(c => {
        html += `<div style="margin-bottom:16px;">`;
        html += `<div style="font-size:15px;font-weight:700;color:var(--text);margin-bottom:6px;border-bottom:1px solid var(--border-light);padding-bottom:4px;">${c}</div>`;
        const years = Object.keys(data.pivotCountry[c]).sort((a,b) => b - a); // Descending years
        years.forEach(y => {
          html += `
            <div style="display:flex;justify-content:space-between;padding:6px 0;">
              <span style="font-size:14px;color:var(--text-secondary);">Year ${y}</span>
              <span style="font-size:14px;font-weight:700;color:var(--primary);">${data.pivotCountry[c][y]} <span style="font-size:11px;font-weight:500;">days</span></span>
            </div>
          `;
        });
        html += `</div>`;
      });
    }
    
    return html;
  }

  // ─── Exports ────────────────────────────────────────────────────────────────
  function copyTextReport(data) {
    const text = generateTextReport(data);
    copyToClipboard(text);
    showToast('Report copied to clipboard', 'success');
  }

  function shareWhatsApp(data) {
     const text = generateTextReport(data);
     copyToClipboard(text);
     showToast('Copied specifically for WhatsApp!', 'success');
  }

  function generateTextReport(data) {
     if (Object.keys(data.pivotYear).length === 0) return 'No data to share.';
     
     let text = `✈️ *Travel Summary: ${state.selectedPassenger}*\n━━━━━━━━━━━━━━\n`;
     if (state.pivotMode === 'year') {
       const years = Object.keys(data.pivotYear).sort((a,b) => b - a);
       years.forEach(y => {
         text += `\n📅 *Year ${y}*\n`;
         Object.keys(data.pivotYear[y]).sort((a,b) => data.pivotYear[y][b] - data.pivotYear[y][a]).forEach(c => {
           text += `   📍 ${c}: ${data.pivotYear[y][c]} days\n`;
         });
       });
     } else {
       const countries = Object.keys(data.pivotCountry).sort();
       countries.forEach(c => {
         text += `\n📍 *${c}*\n`;
         Object.keys(data.pivotCountry[c]).sort((a,b) => b - a).forEach(y => {
           text += `   📅 Year ${y}: ${data.pivotCountry[c][y]} days\n`;
         });
       });
     }
     text += `\n_Generated by Family Hub PWA_`;
     return text;
  }

  async function exportImage() {
    const target = sheet.querySelector('#summary-render-target');
    if (!target) return;
    
    showToast('Generating image…', 'info');
    
    if (!window.html2canvas) {
      await new Promise(resolve => {
        const script = document.createElement('script');
        script.src = 'https://cdnjs.cloudflare.com/ajax/libs/html2canvas/1.4.1/html2canvas.min.js';
        script.onload = resolve;
        document.head.appendChild(script);
      });
    }

    try {
      const canvas = await window.html2canvas(target, { 
        scale: 2, 
        backgroundColor: '#f8fafc' 
      });
      const dataUrl = canvas.toDataURL('image/jpeg', 0.9);
      
      const a = document.createElement('a');
      a.href = dataUrl;
      a.download = `Travel_Summary_${state.selectedPassenger.replace(/ /g, '_')}_${Date.now()}.jpg`;
      a.click();
      showToast('Image downloaded!', 'success');
    } catch(err) {
      console.error(err);
      showToast('Failed to create image', 'error');
    }
  }

  renderUI();
  // Animate in
  setTimeout(() => sheet.classList.add('open'), 10);
}
